In [144]:
import sys
import numpy as np
import pandas as pd
import os


In [170]:
particle_positions = []
with open(os.path.join('.', "sed_N8000_phi0.05_FD.txt"), 'r') as file:
                
    # Read the file line by line
    frame_positions = []
    row_count = 0
    for line in file:
        if row_count % 8003 == 0:
            N = int(line)
        elif row_count % 8003 == 1:
            box_sizes = np.array([float(x) for x in line.split()])
        elif line.strip():
            frame_positions.append([float(x) for x in line.split()])
        else:
            # Process the completed frame
            particle_positions.append(np.array(frame_positions))
            frame_positions = []
        row_count += 1

In [171]:
test = np.array(particle_positions)
test.shape

(101, 8000, 3)

In [147]:
test[0].shape

(8000, 3)

In [148]:
test[1]

array([[  0.85267,  42.849  ,  42.19775],
       [-10.50106,  34.65663,   1.1847 ],
       [-28.06033,  10.77221, -43.39636],
       ...,
       [-32.26804, -36.08074, -13.22014],
       [ 31.74264,  20.35339,  17.20762],
       [-27.1304 ,  36.04449,  35.69645]])

In [149]:
test[2]

array([[  0.61521,  36.60965,  41.12437],
       [-11.20574,  35.20311,   3.92434],
       [-39.94965,  13.2933 , -43.03162],
       ...,
       [-38.52673, -33.02922, -13.51146],
       [ 28.05224,  15.85412,  14.47888],
       [-28.71306,  35.80181,  33.80283]])

In [150]:
test_diff = test[2] - test[1]
test_diff.shape

(8000, 3)

In [151]:
test_diff

array([[ -0.23746,  -6.23935,  -1.07338],
       [ -0.70468,   0.54648,   2.73964],
       [-11.88932,   2.52109,   0.36474],
       ...,
       [ -6.25869,   3.05152,  -0.29132],
       [ -3.6904 ,  -4.49927,  -2.72874],
       [ -1.58266,  -0.24268,  -1.89362]])

In [152]:
def unwrap_trajectory(particle_positions, box_sizes):
    # Compute displacement between frames
    delta_x = np.diff(particle_positions, axis=0)
    
    # Get nearest image displacement
    delta_x -= np.fix(2 * delta_x / box_sizes) * box_sizes
    
    # Take cumulative sum of displacements
    unwrapped_positions = np.cumsum(delta_x, axis=0)
    
    return unwrapped_positions



In [181]:
delta_x = np.diff(particle_positions, axis=0)
delta_x -= np.fix(2 * delta_x / box_sizes) * box_sizes
print(delta_x[1] - test_diff)
print(delta_x.shape)
# print(delta_x[0])
mean_delta_x = np.mean(delta_x[0], axis = 0)
print(mean_delta_x)

print(box_sizes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(100, 8000, 3)
[-0.00691704 -0.0037672  -1.02437713]
[87.51239 87.51239 87.51239]


In [185]:
mean_delta_x = np.mean(delta_x, axis = 1)
print(mean_delta_x)

[[-6.91703750e-03 -3.76720125e-03 -1.02437713e+00]
 [-3.33969350e-02 -3.27504237e-02 -1.01267985e+00]
 [-9.71202600e-02 -4.61271150e-02 -1.00663512e+00]
 [-3.51672525e-02 -1.74120675e-02 -1.00500354e+00]
 [-4.02707837e-02  4.18664950e-02 -9.43567897e-01]
 [ 9.14939037e-02 -4.11723250e-02 -1.02392624e+00]
 [ 7.51157212e-02 -1.49705625e-03 -1.10085503e+00]
 [ 1.02546878e-01  2.49253362e-02 -1.04109809e+00]
 [ 7.53068250e-03  6.59275438e-02 -9.44970960e-01]
 [-4.18045575e-02 -5.20424113e-02 -9.16053746e-01]
 [-3.61202750e-02  7.52589650e-02 -9.32142202e-01]
 [ 5.98837325e-02 -2.21125113e-02 -1.05601567e+00]
 [-5.39707338e-02 -4.01774400e-02 -9.91103866e-01]
 [-2.65938750e-02  2.98370737e-02 -1.05618957e+00]
 [ 2.03755925e-02 -6.34067625e-03 -9.61081911e-01]
 [-2.54227038e-02  2.00990062e-02 -9.62609909e-01]
 [ 1.83550050e-02 -7.68831875e-03 -9.38221037e-01]
 [-2.79511913e-02 -1.00335000e-03 -9.01857885e-01]
 [-3.35985150e-02  3.27915538e-02 -1.08811176e+00]
 [-9.86728600e-02 -3.62056550e-

In [186]:
unwrapped_positions = np.cumsum(mean_delta_x, axis=0)
print(unwrapped_positions.shape)
print(unwrapped_positions)

(100, 3)
[[-6.91703750e-03 -3.76720125e-03 -1.02437713e+00]
 [-4.03139725e-02 -3.65176250e-02 -2.03705699e+00]
 [-1.37434233e-01 -8.26447400e-02 -3.04369211e+00]
 [-1.72601485e-01 -1.00056807e-01 -4.04869565e+00]
 [-2.12872269e-01 -5.81903125e-02 -4.99226354e+00]
 [-1.21378365e-01 -9.93626375e-02 -6.01618979e+00]
 [-4.62626438e-02 -1.00859694e-01 -7.11704481e+00]
 [ 5.62842337e-02 -7.59343575e-02 -8.15814290e+00]
 [ 6.38149162e-02 -1.00068137e-02 -9.10311386e+00]
 [ 2.20103587e-02 -6.20492250e-02 -1.00191676e+01]
 [-1.41099163e-02  1.32097400e-02 -1.09513098e+01]
 [ 4.57738162e-02 -8.90277125e-03 -1.20073255e+01]
 [-8.19691750e-03 -4.90802113e-02 -1.29984293e+01]
 [-3.47907925e-02 -1.92431375e-02 -1.40546189e+01]
 [-1.44152000e-02 -2.55838138e-02 -1.50157008e+01]
 [-3.98379038e-02 -5.48480750e-03 -1.59783107e+01]
 [-2.14828988e-02 -1.31731263e-02 -1.69165318e+01]
 [-4.94340900e-02 -1.41764763e-02 -1.78183897e+01]
 [-8.30326050e-02  1.86150775e-02 -1.89065014e+01]
 [-1.81705465e-01 -1.7

In [161]:
# average over particles
mean_displacement = np.mean(unwrapped_positions, axis=1)
mean_displacement_abs = np.abs(mean_displacement)
mean_displacement_abs

array([[6.91703750e-03, 3.76720125e-03, 1.02437713e+00],
       [4.03139725e-02, 3.65176250e-02, 2.03705699e+00],
       [1.37434232e-01, 8.26447400e-02, 3.04369211e+00],
       [1.72601485e-01, 1.00056808e-01, 4.04869565e+00],
       [2.12872269e-01, 5.81903125e-02, 4.99226354e+00],
       [1.21378365e-01, 9.93626375e-02, 6.01618979e+00],
       [4.62626438e-02, 1.00859694e-01, 7.11704481e+00],
       [5.62842337e-02, 7.59343575e-02, 8.15814290e+00],
       [6.38149162e-02, 1.00068137e-02, 9.10311386e+00],
       [2.20103587e-02, 6.20492250e-02, 1.00191676e+01],
       [1.41099163e-02, 1.32097400e-02, 1.09513098e+01],
       [4.57738163e-02, 8.90277125e-03, 1.20073255e+01],
       [8.19691750e-03, 4.90802113e-02, 1.29984294e+01],
       [3.47907925e-02, 1.92431375e-02, 1.40546189e+01],
       [1.44152000e-02, 2.55838137e-02, 1.50157008e+01],
       [3.98379038e-02, 5.48480750e-03, 1.59783107e+01],
       [2.14828987e-02, 1.31731263e-02, 1.69165318e+01],
       [4.94340900e-02, 1.41764

In [187]:
velocity = np.polyfit(np.arange(len(mean_displacement)), mean_displacement, 1)[0]

# Convert displacement to velocity
time_interval = 10 
velocity /= time_interval
velocity

array([ 0.00022721,  0.0002331 , -0.10026519])

In [157]:
def compute_mean_displacement(unwrapped_positions):
    # Average trajectories over all particles
    mean_displacement = np.mean(unwrapped_positions, axis=1)
    
    return mean_displacement

def compute_velocity(mean_displacement, time_interval):
    # Fit a straight line to the displacement to compute velocity
    velocity = np.polyfit(np.arange(len(mean_displacement)), mean_displacement, 1)[0]
    
    # Convert displacement to velocity (assuming time_interval is 1)
    velocity /= time_interval
    
    return velocity

In [158]:
# Initialize arrays to store mean displacements and velocities for each frame
mean_displacements = []
velocities = []

# Loop through frames
for frame_positions in particle_positions:  # Loop through frames
    # Unwrap trajectory for the frame
    unwrapped_positions = unwrap_trajectory(particle_positions, box_sizes)
    
    # Compute mean displacement for the frame
    mean_displacement = compute_mean_displacement(unwrapped_positions)
    
    # Compute velocity for the frame
    velocity = compute_velocity(mean_displacement, 1)
    
    # Append mean displacement and velocity to lists
    mean_displacements.append(mean_displacement)
    average_velocity = velocities.append(velocity)

average_velocity

-0.33268291845351267